### ISSUE TITLE
crash on Pop!_OS 21.10 with ulauncher v5.14.2

### ISSUE THREAD

**Issue by mschaaf** [Ulauncher/ulauncher-timer#16]
The crash happens on installation:

Message: Extension ID: com.github.ulauncher.ulauncher-emoji
Error Name: UnhandledError
Type: ExtensionIsRunningError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 202, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 446, in prefs_extension_add
    ExtensionRunner.get_instance().run(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionRunner.py", line 68, in run
    raise ExtensionIsRunningError('Extension ID: %s' % extension_id)
ulauncher.api.server.ExtensionRunner.ExtensionIsRunningError: Extension ID: com.github.ulauncher.ulauncher-emoji

```

**Comment by mschaaf** [comment]
I am closing as I see now the error. It seems that a previous extension error is shown on the installation of ulauncher-timer.
Maybe launcher itself mixes ups errors between extensions.
